/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Defines the properties and methods of an address.
 *
 */
class Address {
  /**
   * Create a Address.
   * @member {string} address1 The first line of the street address.
   * Typcically contains
   * the number and street name.
   * @member {string} [address2] The second line of the street address.
   * Typically contains
   * an apartment number, suite number or department.
   * @member {string} city The city where the address is situated.
   * @member {string} state The state where the address is located.
   * @member {string} zipCode The postal code for the address.
   */
  constructor() {
  }

  /**
   * Defines the metadata of Address
   *
   * @returns {object} metadata of Address
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'Address',
      type: {
        name: 'Composite',
        className: 'Address',
        modelProperties: {
          address1: {
            required: true,
            serializedName: 'address1',
            type: {
              name: 'String'
            }
          },
          address2: {
            required: false,
            serializedName: 'address2',
            type: {
              name: 'String'
            }
          },
          city: {
            required: true,
            serializedName: 'city',
            type: {
              name: 'String'
            }
          },
          state: {
            required: true,
            serializedName: 'state',
            type: {
              name: 'String'
            }
          },
          zipCode: {
            required: true,
            serializedName: 'zipCode',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = Address;
