/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * The response model that is returned to the client when a new bank account is
 * added
 * to the platform
 *
 */
class BankAccountResponseModel {
  /**
   * Create a BankAccountResponseModel.
   * @member {string} [token] The payment token for the bank account.
   * @member {string} [bankAccountState] The state that the bank acocunt is in.
   * Possible values include: 'Unknown', 'New', 'Pending', 'Authorized',
   * 'Disabled'
   * @member {string} [redirectUrl] The url that the client will be redirected
   * to after the bank account has been created.
   */
  constructor() {
  }

  /**
   * Defines the metadata of BankAccountResponseModel
   *
   * @returns {object} metadata of BankAccountResponseModel
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'BankAccountResponseModel',
      type: {
        name: 'Composite',
        className: 'BankAccountResponseModel',
        modelProperties: {
          token: {
            required: false,
            serializedName: 'token',
            type: {
              name: 'String'
            }
          },
          bankAccountState: {
            required: false,
            serializedName: 'bankAccountState',
            type: {
              name: 'String'
            }
          },
          redirectUrl: {
            required: false,
            serializedName: 'redirectUrl',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = BankAccountResponseModel;
