/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Defines a BIN (bank identification number)
 *
 */
class Bin {
  /**
   * Create a Bin.
   * @member {string} [bin] Gets the bin.
   * @member {string} [brand] Gets or sets the brand. Possible values include:
   * 'Unknown', 'Visa', 'MasterCard', 'Amex', 'Discover'
   * @member {boolean} [isDebitCard] Gets or sets a value indicating whether
   * this instance is debit.
   * @member {boolean} [isCheckCard] Gets or sets a value indicating whether
   * this instance is check card.
   * @member {boolean} [isGiftCard] Gets or sets a value indicating whether
   * this instance is gift card.
   * @member {boolean} [isCorporateCard] Gets or sets a value indicating
   * whether this instance is corporate card.
   * @member {boolean} [isFleetCard] Gets or sets a value indicating whether
   * this instance is fleet card.
   * @member {boolean} [isPrepaidCard] Gets or sets a value indicating whether
   * this instance is prepaid card.
   */
  constructor() {
  }

  /**
   * Defines the metadata of Bin
   *
   * @returns {object} metadata of Bin
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'Bin',
      type: {
        name: 'Composite',
        className: 'Bin',
        modelProperties: {
          bin: {
            required: false,
            serializedName: 'bin',
            type: {
              name: 'String'
            }
          },
          brand: {
            required: false,
            readOnly: true,
            serializedName: 'brand',
            type: {
              name: 'String'
            }
          },
          isDebitCard: {
            required: false,
            serializedName: 'isDebitCard',
            type: {
              name: 'Boolean'
            }
          },
          isCheckCard: {
            required: false,
            serializedName: 'isCheckCard',
            type: {
              name: 'Boolean'
            }
          },
          isGiftCard: {
            required: false,
            serializedName: 'isGiftCard',
            type: {
              name: 'Boolean'
            }
          },
          isCorporateCard: {
            required: false,
            serializedName: 'isCorporateCard',
            type: {
              name: 'Boolean'
            }
          },
          isFleetCard: {
            required: false,
            serializedName: 'isFleetCard',
            type: {
              name: 'Boolean'
            }
          },
          isPrepaidCard: {
            required: false,
            serializedName: 'isPrepaidCard',
            type: {
              name: 'Boolean'
            }
          }
        }
      }
    };
  }
}

module.exports = Bin;
