/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * Checkout request model
 *
 */
class CheckoutRequestModel {
  /**
   * Create a CheckoutRequestModel.
   * @member {string} [redirectUrl] Gets or sets the redirect URL.
   * @member {string} [referenceId] Gets or sets the reference identifier.
   * @member {number} [amount] Gets or sets the amount.
   * @member {string} [nameOnAccount] Gets or sets the name on account.
   * @member {date} [expirationDate] Gets or sets the expiration date.
   * @member {boolean} [enableBillingInformation] Gets or sets a value
   * indicating whether [enable billing information].
   * @member {object} [billingAddress] Gets or sets the billing address.
   * @member {string} [billingAddress.address1] The first line of the street
   * address.  Typcically contains
   * the number and street name.
   * @member {string} [billingAddress.address2] The second line of the street
   * address.  Typically contains
   * an apartment number, suite number or department.
   * @member {string} [billingAddress.city] The city where the address is
   * situated.
   * @member {string} [billingAddress.state] The state where the address is
   * located.
   * @member {string} [billingAddress.zipCode] The postal code for the address.
   * @member {string} [email] Gets or sets the email.
   * @member {boolean} [requireEmail] Gets or sets a value indicating whether
   * [require email].
   * @member {boolean} [enableSaveOption] Gets or sets a value indicating
   * whether [enable save option].
   */
  constructor() {
  }

  /**
   * Defines the metadata of CheckoutRequestModel
   *
   * @returns {object} metadata of CheckoutRequestModel
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'CheckoutRequestModel',
      type: {
        name: 'Composite',
        className: 'CheckoutRequestModel',
        modelProperties: {
          redirectUrl: {
            required: false,
            serializedName: 'redirectUrl',
            type: {
              name: 'String'
            }
          },
          referenceId: {
            required: false,
            serializedName: 'referenceId',
            type: {
              name: 'String'
            }
          },
          amount: {
            required: false,
            serializedName: 'amount',
            type: {
              name: 'Number'
            }
          },
          nameOnAccount: {
            required: false,
            serializedName: 'nameOnAccount',
            type: {
              name: 'String'
            }
          },
          expirationDate: {
            required: false,
            serializedName: 'expirationDate',
            type: {
              name: 'DateTime'
            }
          },
          enableBillingInformation: {
            required: false,
            serializedName: 'enableBillingInformation',
            type: {
              name: 'Boolean'
            }
          },
          billingAddress: {
            required: false,
            serializedName: 'billingAddress',
            type: {
              name: 'Composite',
              className: 'Address'
            }
          },
          email: {
            required: false,
            serializedName: 'email',
            type: {
              name: 'String'
            }
          },
          requireEmail: {
            required: false,
            serializedName: 'requireEmail',
            type: {
              name: 'Boolean'
            }
          },
          enableSaveOption: {
            required: false,
            serializedName: 'enableSaveOption',
            type: {
              name: 'Boolean'
            }
          }
        }
      }
    };
  }
}

module.exports = CheckoutRequestModel;
