/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * The request model sent by the client for adding new credit cards to the
 * payment platform.
 *
 */
class CreditCardRequestModel {
  /**
   * Create a CreditCardRequestModel.
   * @member {string} cardNumber The number on the credit card.
   * @member {string} securityCode The security, or CVV code, on the card.
   * @member {number} expirationMonth The expiration month of the credit card.
   * @member {number} expirationYear The expiration year of the credit card.
   * @member {string} cardHolderName The name of the cardholder, as it appears
   * on the front of the credit card.
   * @member {object} billingAddress The billing address for the credit card
   * holder..
   * @member {string} [billingAddress.address1] The first line of the street
   * address.  Typcically contains
   * the number and street name.
   * @member {string} [billingAddress.address2] The second line of the street
   * address.  Typically contains
   * an apartment number, suite number or department.
   * @member {string} [billingAddress.city] The city where the address is
   * situated.
   * @member {string} [billingAddress.state] The state where the address is
   * located.
   * @member {string} [billingAddress.zipCode] The postal code for the address.
   * @member {string} email A valid email address for the card holder.
   * @member {string} [referenceId] The client application provided reference
   * ID for the credit card.
   * @member {string} [redirectUrl] The url that the client will be redirected
   * to after the credit card has been created.
   */
  constructor() {
  }

  /**
   * Defines the metadata of CreditCardRequestModel
   *
   * @returns {object} metadata of CreditCardRequestModel
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'CreditCardRequestModel',
      type: {
        name: 'Composite',
        className: 'CreditCardRequestModel',
        modelProperties: {
          cardNumber: {
            required: true,
            serializedName: 'cardNumber',
            type: {
              name: 'String'
            }
          },
          securityCode: {
            required: true,
            serializedName: 'securityCode',
            constraints: {
              Pattern: '\d{3,4}'
            },
            type: {
              name: 'String'
            }
          },
          expirationMonth: {
            required: true,
            serializedName: 'expirationMonth',
            constraints: {
              InclusiveMaximum: 12,
              InclusiveMinimum: 1
            },
            type: {
              name: 'Number'
            }
          },
          expirationYear: {
            required: true,
            serializedName: 'expirationYear',
            constraints: {
              InclusiveMaximum: 2038,
              InclusiveMinimum: 2018
            },
            type: {
              name: 'Number'
            }
          },
          cardHolderName: {
            required: true,
            serializedName: 'cardHolderName',
            type: {
              name: 'String'
            }
          },
          billingAddress: {
            required: true,
            serializedName: 'billingAddress',
            type: {
              name: 'Composite',
              className: 'Address'
            }
          },
          email: {
            required: true,
            serializedName: 'email',
            type: {
              name: 'String'
            }
          },
          referenceId: {
            required: false,
            serializedName: 'referenceId',
            type: {
              name: 'String'
            }
          },
          redirectUrl: {
            required: false,
            serializedName: 'redirectUrl',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = CreditCardRequestModel;
