/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * The response model sent to the client when a new credit card is added to the
 * platform.
 *
 */
class CreditCardResponseModel {
  /**
   * Create a CreditCardResponseModel.
   * @member {string} [token] The payment token for the credit card
   * @member {string} [cardState] The state that the credit card is in.
   * Possible values include: 'Unknown', 'New', 'Authorized', 'Expired',
   * 'Deleted', 'Invalid'
   * @member {string} [code] The pre-authorization result code.
   * @member {string} [message] The pre-authorization result message.
   * @member {string} [redirectUrl] The URL that the client will be redirected
   * to after the credit card has been created.
   */
  constructor() {
  }

  /**
   * Defines the metadata of CreditCardResponseModel
   *
   * @returns {object} metadata of CreditCardResponseModel
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'CreditCardResponseModel',
      type: {
        name: 'Composite',
        className: 'CreditCardResponseModel',
        modelProperties: {
          token: {
            required: false,
            serializedName: 'token',
            type: {
              name: 'String'
            }
          },
          cardState: {
            required: false,
            serializedName: 'cardState',
            type: {
              name: 'String'
            }
          },
          code: {
            required: false,
            serializedName: 'code',
            type: {
              name: 'String'
            }
          },
          message: {
            required: false,
            serializedName: 'message',
            type: {
              name: 'String'
            }
          },
          redirectUrl: {
            required: false,
            serializedName: 'redirectUrl',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = CreditCardResponseModel;
