/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Defines a a funding source for a payment request.
 *
 */
class PaymentMethodModel {
  /**
   * Create a PaymentMethodModel.
   * @member {string} paymentToken The credit card or bank account token that
   * will be used for payment.
   * @member {string} type The type of funding source that will be used for the
   * payment. Possible values include: 'Unknown', 'Credit Card', 'ACH'
   */
  constructor() {
  }

  /**
   * Defines the metadata of PaymentMethodModel
   *
   * @returns {object} metadata of PaymentMethodModel
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'PaymentMethodModel',
      type: {
        name: 'Composite',
        className: 'PaymentMethodModel',
        modelProperties: {
          paymentToken: {
            required: true,
            serializedName: 'paymentToken',
            type: {
              name: 'String'
            }
          },
          type: {
            required: true,
            serializedName: 'type',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = PaymentMethodModel;
