/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Defines a payment filter when requesting a collection of payments
 *
 */
class PaymentFilter {
  /**
   * Create a PaymentFilter.
   * @member {string} referenceId The client application provided reference ID
   * for the payment.
   * @member {date} [minDate] The optional lower bound of the range for payment
   * date.
   * @member {date} [maxDate] The optional upper bound of the range for payment
   * date.
   */
  constructor() {
  }

  /**
   * Defines the metadata of PaymentFilter
   *
   * @returns {object} metadata of PaymentFilter
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'PaymentFilter',
      type: {
        name: 'Composite',
        className: 'PaymentFilter',
        modelProperties: {
          referenceId: {
            required: true,
            serializedName: 'referenceId',
            type: {
              name: 'String'
            }
          },
          minDate: {
            required: false,
            serializedName: 'minDate',
            type: {
              name: 'DateTime'
            }
          },
          maxDate: {
            required: false,
            serializedName: 'maxDate',
            type: {
              name: 'DateTime'
            }
          }
        }
      }
    };
  }
}

module.exports = PaymentFilter;
