/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * The model sent to the client as a part of the payment model.
 * Provides details on the payment result.
 *
 */
class PaymentResultModel {
  /**
   * Create a PaymentResultModel.
   * @member {string} [status] The current status of the payment. Possible
   * values include: 'Unknown', 'New', 'Authorized', 'Captured', 'Expired',
   * 'Declined', 'Failed', 'Cancelled', 'Charge Back', 'Refunded', 'Partially
   * Refunded'
   * @member {string} [code] The payment result code.
   * @member {string} [message] The payment result message.
   * @member {string} [providerAccountId] The unique ID of the provider account
   * that was used to make this payment.
   * @member {string} [merchantTransactionId] Tthe merchant transaction
   * identifier.
   * @member {number} [merchantTransactionFee] The merchant transaction fee.
   */
  constructor() {
  }

  /**
   * Defines the metadata of PaymentResultModel
   *
   * @returns {object} metadata of PaymentResultModel
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'PaymentResultModel',
      type: {
        name: 'Composite',
        className: 'PaymentResultModel',
        modelProperties: {
          status: {
            required: false,
            serializedName: 'status',
            type: {
              name: 'String'
            }
          },
          code: {
            required: false,
            serializedName: 'code',
            type: {
              name: 'String'
            }
          },
          message: {
            required: false,
            serializedName: 'message',
            type: {
              name: 'String'
            }
          },
          providerAccountId: {
            required: false,
            serializedName: 'providerAccountId',
            type: {
              name: 'String'
            }
          },
          merchantTransactionId: {
            required: false,
            serializedName: 'merchantTransactionId',
            type: {
              name: 'String'
            }
          },
          merchantTransactionFee: {
            required: false,
            serializedName: 'merchantTransactionFee',
            type: {
              name: 'Number'
            }
          }
        }
      }
    };
  }
}

module.exports = PaymentResultModel;
