/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * The request model sent by the client to add a new refund to the platform.
 *
 */
class RefundRequestModel {
  /**
   * Create a RefundRequestModel.
   * @member {number} [amount] The amount to be refunded.  If an amount less
   * than the original payment amount is
   * specified, a partial refund will be processed.  If no amount is specified,
   * a full refund
   * will be processed.
   * @member {string} reason The reason for issuing the refund.
   */
  constructor() {
  }

  /**
   * Defines the metadata of RefundRequestModel
   *
   * @returns {object} metadata of RefundRequestModel
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'RefundRequestModel',
      type: {
        name: 'Composite',
        className: 'RefundRequestModel',
        modelProperties: {
          amount: {
            required: false,
            serializedName: 'amount',
            type: {
              name: 'Number'
            }
          },
          reason: {
            required: true,
            serializedName: 'reason',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = RefundRequestModel;
