/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * The model sent to the client as a part of the payment model.
 * Provides details on the refund result.
 *
 */
class RefundResultModel {
  /**
   * Create a RefundResultModel.
   * @member {string} [status] The current status of the refund. Possible
   * values include: 'Unknown', 'New', 'Authorized', 'Captured', 'Expired',
   * 'Declined', 'Failed', 'Cancelled', 'Charge Back', 'Refunded', 'Partially
   * Refunded'
   * @member {string} [code] The refund result code.
   * @member {string} [message] The refund result message.
   * @member {string} [merchantTransactionId] The Merchant Transaction ID
   * number for the payment that is being refunded.
   * @member {string} [providerAccountId] The unique ID of the provider account
   * that was used to make this refund.
   * @member {number} [amount] The amount to be refunded.  If an amount less
   * than the original payment amount is
   * specified, a partial refund will be processed.  If no amount is specified,
   * a full refund
   * will be processed.
   * @member {string} [reason] The reason for issuing the refund.
   * @member {date} [createdDate] The timestamp indicating when the refund was
   * created.
   */
  constructor() {
  }

  /**
   * Defines the metadata of RefundResultModel
   *
   * @returns {object} metadata of RefundResultModel
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'RefundResultModel',
      type: {
        name: 'Composite',
        className: 'RefundResultModel',
        modelProperties: {
          status: {
            required: false,
            serializedName: 'status',
            type: {
              name: 'String'
            }
          },
          code: {
            required: false,
            serializedName: 'code',
            type: {
              name: 'String'
            }
          },
          message: {
            required: false,
            serializedName: 'message',
            type: {
              name: 'String'
            }
          },
          merchantTransactionId: {
            required: false,
            serializedName: 'merchantTransactionId',
            type: {
              name: 'String'
            }
          },
          providerAccountId: {
            required: false,
            serializedName: 'providerAccountId',
            type: {
              name: 'String'
            }
          },
          amount: {
            required: false,
            serializedName: 'amount',
            type: {
              name: 'Number'
            }
          },
          reason: {
            required: false,
            serializedName: 'reason',
            type: {
              name: 'String'
            }
          },
          createdDate: {
            required: false,
            serializedName: 'createdDate',
            type: {
              name: 'DateTime'
            }
          }
        }
      }
    };
  }
}

module.exports = RefundResultModel;
