/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * The model sent to the client in response to a GET request for a payment
 * subscription.
 *
 */
class SubscriptionModel {
  /**
   * Create a SubscriptionModel.
   * @member {number} [id] The id of the payment subscription.
   * @member {string} [name] The name of payment subscription.
   * @member {string} [description] The description of payment subscription.
   * @member {object} [properties] The properties of the payment subscription.
   * @member {number} [runDay] The process day of the payment subscription.
   * @member {string} [state] The state that payment subscription is in.
   * Possible values include: 'Active', 'Inactive', 'Expired'
   * @member {string} [paymentType] The payment type of the payment
   * subscription. Possible values include: 'Unknown', 'Credit Card', 'ACH'
   * @member {string} [paymentToken] The payment token of the payment
   * subscription.
   * @member {string} [amountType] The amount type of the payment subscription.
   * Possible values include: 'Fixed', 'Dynamic'
   * @member {number} [amount] The amount of money to be charged by the payment
   * subscription.
   * @member {string} [amountWebServiceURL] The url of web api to use to
   * retrieve the amount to be charged by the payment subscription.
   * @member {string} [callbackWebServiceURL] The url of a web api to use to
   * post back notifications each time payment subscription is processed.
   * @member {string} [referenceId] The client application provided reference
   * ID for the credit card.
   * @member {date} [lastProcessed] The timestamp indicating when the
   * subscription was last processed.
   * @member {date} [endDate] The date indicating when the payment subscription
   * should be stopped.
   * @member {date} [createdTime] The timestamp indicating when the credit card
   * was created.
   * @member {date} [modifiedTime] The timestamp indicating the last time that
   * the details of the credit card were modified.
   */
  constructor() {
  }

  /**
   * Defines the metadata of SubscriptionModel
   *
   * @returns {object} metadata of SubscriptionModel
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'SubscriptionModel',
      type: {
        name: 'Composite',
        className: 'SubscriptionModel',
        modelProperties: {
          id: {
            required: false,
            serializedName: 'id',
            type: {
              name: 'Number'
            }
          },
          name: {
            required: false,
            serializedName: 'name',
            type: {
              name: 'String'
            }
          },
          description: {
            required: false,
            serializedName: 'description',
            type: {
              name: 'String'
            }
          },
          properties: {
            required: false,
            serializedName: 'properties',
            type: {
              name: 'Dictionary',
              value: {
                  required: false,
                  serializedName: 'StringElementType',
                  type: {
                    name: 'String'
                  }
              }
            }
          },
          runDay: {
            required: false,
            serializedName: 'runDay',
            type: {
              name: 'Number'
            }
          },
          state: {
            required: false,
            serializedName: 'state',
            type: {
              name: 'String'
            }
          },
          paymentType: {
            required: false,
            serializedName: 'paymentType',
            type: {
              name: 'String'
            }
          },
          paymentToken: {
            required: false,
            serializedName: 'paymentToken',
            type: {
              name: 'String'
            }
          },
          amountType: {
            required: false,
            serializedName: 'amountType',
            type: {
              name: 'String'
            }
          },
          amount: {
            required: false,
            serializedName: 'amount',
            type: {
              name: 'Number'
            }
          },
          amountWebServiceURL: {
            required: false,
            serializedName: 'amountWebServiceURL',
            type: {
              name: 'String'
            }
          },
          callbackWebServiceURL: {
            required: false,
            serializedName: 'callbackWebServiceURL',
            type: {
              name: 'String'
            }
          },
          referenceId: {
            required: false,
            serializedName: 'referenceId',
            type: {
              name: 'String'
            }
          },
          lastProcessed: {
            required: false,
            serializedName: 'lastProcessed',
            type: {
              name: 'DateTime'
            }
          },
          endDate: {
            required: false,
            serializedName: 'endDate',
            type: {
              name: 'DateTime'
            }
          },
          createdTime: {
            required: false,
            serializedName: 'createdTime',
            type: {
              name: 'DateTime'
            }
          },
          modifiedTime: {
            required: false,
            serializedName: 'modifiedTime',
            type: {
              name: 'DateTime'
            }
          }
        }
      }
    };
  }
}

module.exports = SubscriptionModel;
