/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * The request model sent by the client for adding new subscription to the
 * payment platform.
 *
 */
class SubscriptionRequestModel {
  /**
   * Create a SubscriptionRequestModel.
   * @member {string} name The name of payment subscription.
   * @member {string} [description] The description of payment subscription.
   * @member {object} [properties] The properties of the payment subscription.
   * @member {number} runDay The process day of the payment subscription.
   * @member {string} state The state that payment subscription is in. Possible
   * values include: 'Active', 'Inactive', 'Expired'
   * @member {string} paymentType The payment type of the payment subscription.
   * Possible values include: 'Unknown', 'Credit Card', 'ACH'
   * @member {string} paymentToken The payment token of the payment
   * subscription.
   * @member {string} amountType The amount type of the payment subscription.
   * Possible values include: 'Fixed', 'Dynamic'
   * @member {number} [amount] The amount of money to be charged by the payment
   * subscription.
   * @member {string} [amountWebServiceURL] The url of web api to use to
   * retrieve the amount to be charged by the payment subscription.
   * @member {string} [callbackWebServiceURL] The url of a web api to use to
   * post back notifications each time payment subscription is processed.
   * @member {date} [endDate] The date indicating when the payment subscription
   * should be stopped.
   * @member {string} [referenceId] The client application provided reference
   * ID for the credit card.
   */
  constructor() {
  }

  /**
   * Defines the metadata of SubscriptionRequestModel
   *
   * @returns {object} metadata of SubscriptionRequestModel
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'SubscriptionRequestModel',
      type: {
        name: 'Composite',
        className: 'SubscriptionRequestModel',
        modelProperties: {
          name: {
            required: true,
            serializedName: 'name',
            type: {
              name: 'String'
            }
          },
          description: {
            required: false,
            serializedName: 'description',
            type: {
              name: 'String'
            }
          },
          properties: {
            required: false,
            serializedName: 'properties',
            type: {
              name: 'Dictionary',
              value: {
                  required: false,
                  serializedName: 'StringElementType',
                  type: {
                    name: 'String'
                  }
              }
            }
          },
          runDay: {
            required: true,
            serializedName: 'runDay',
            constraints: {
              InclusiveMaximum: 31,
              InclusiveMinimum: 1
            },
            type: {
              name: 'Number'
            }
          },
          state: {
            required: true,
            serializedName: 'state',
            type: {
              name: 'String'
            }
          },
          paymentType: {
            required: true,
            serializedName: 'paymentType',
            type: {
              name: 'String'
            }
          },
          paymentToken: {
            required: true,
            serializedName: 'paymentToken',
            type: {
              name: 'String'
            }
          },
          amountType: {
            required: true,
            serializedName: 'amountType',
            type: {
              name: 'String'
            }
          },
          amount: {
            required: false,
            serializedName: 'amount',
            type: {
              name: 'Number'
            }
          },
          amountWebServiceURL: {
            required: false,
            serializedName: 'amountWebServiceURL',
            type: {
              name: 'String'
            }
          },
          callbackWebServiceURL: {
            required: false,
            serializedName: 'callbackWebServiceURL',
            type: {
              name: 'String'
            }
          },
          endDate: {
            required: false,
            serializedName: 'endDate',
            type: {
              name: 'DateTime'
            }
          },
          referenceId: {
            required: false,
            serializedName: 'referenceId',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = SubscriptionRequestModel;
