/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * The request model sent by the client for updating credit cards in the
 * payment platform.
 *
 */
class UpdateCreditCardModel {
  /**
   * Create a UpdateCreditCardModel.
   * @member {string} token The payment token for the credit card.
   * @member {number} expirationMonth The expiration month of the credit card.
   * @member {number} expirationYear The expiration year of the credit card.
   * @member {string} cardHolderName The name of the cardholder, as it appears
   * on the front of the credit card.
   * @member {object} billingAddress The billing address for the credit card
   * holder..
   * @member {string} [billingAddress.address1] The first line of the street
   * address.  Typcically contains
   * the number and street name.
   * @member {string} [billingAddress.address2] The second line of the street
   * address.  Typically contains
   * an apartment number, suite number or department.
   * @member {string} [billingAddress.city] The city where the address is
   * situated.
   * @member {string} [billingAddress.state] The state where the address is
   * located.
   * @member {string} [billingAddress.zipCode] The postal code for the address.
   * @member {string} email A valid email address for the card holder.
   */
  constructor() {
  }

  /**
   * Defines the metadata of UpdateCreditCardModel
   *
   * @returns {object} metadata of UpdateCreditCardModel
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'UpdateCreditCardModel',
      type: {
        name: 'Composite',
        className: 'UpdateCreditCardModel',
        modelProperties: {
          token: {
            required: true,
            serializedName: 'token',
            type: {
              name: 'String'
            }
          },
          expirationMonth: {
            required: true,
            serializedName: 'expirationMonth',
            constraints: {
              InclusiveMaximum: 12,
              InclusiveMinimum: 1
            },
            type: {
              name: 'Number'
            }
          },
          expirationYear: {
            required: true,
            serializedName: 'expirationYear',
            constraints: {
              InclusiveMaximum: 2038,
              InclusiveMinimum: 2018
            },
            type: {
              name: 'Number'
            }
          },
          cardHolderName: {
            required: true,
            serializedName: 'cardHolderName',
            type: {
              name: 'String'
            }
          },
          billingAddress: {
            required: true,
            serializedName: 'billingAddress',
            type: {
              name: 'Composite',
              className: 'Address'
            }
          },
          email: {
            required: true,
            serializedName: 'email',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = UpdateCreditCardModel;
