/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * The request model sent by the client for updating bank accounts in the
 * payment platform.
 *
 */
class UpdateBankAccountModel {
  /**
   * Create a UpdateBankAccountModel.
   * @member {string} [token] The payment token for the bank account.
   * @member {string} [nickname] The aribtrary nickname of the account, used as
   * a way to identify the account.
   * @member {string} accountHolderName The name of the individual or entity
   * that is autorized to make transactions for the bank account.
   * @member {object} accountHolderAddress The mailing address for the account
   * holder.
   * @member {string} [accountHolderAddress.address1] The first line of the
   * street address.  Typcically contains
   * the number and street name.
   * @member {string} [accountHolderAddress.address2] The second line of the
   * street address.  Typically contains
   * an apartment number, suite number or department.
   * @member {string} [accountHolderAddress.city] The city where the address is
   * situated.
   * @member {string} [accountHolderAddress.state] The state where the address
   * is located.
   * @member {string} [accountHolderAddress.zipCode] The postal code for the
   * address.
   * @member {string} email The email address for the account holder.
   */
  constructor() {
  }

  /**
   * Defines the metadata of UpdateBankAccountModel
   *
   * @returns {object} metadata of UpdateBankAccountModel
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'UpdateBankAccountModel',
      type: {
        name: 'Composite',
        className: 'UpdateBankAccountModel',
        modelProperties: {
          token: {
            required: false,
            serializedName: 'token',
            type: {
              name: 'String'
            }
          },
          nickname: {
            required: false,
            serializedName: 'nickname',
            type: {
              name: 'String'
            }
          },
          accountHolderName: {
            required: true,
            serializedName: 'accountHolderName',
            type: {
              name: 'String'
            }
          },
          accountHolderAddress: {
            required: true,
            serializedName: 'accountHolderAddress',
            type: {
              name: 'Composite',
              className: 'Address'
            }
          },
          email: {
            required: true,
            serializedName: 'email',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = UpdateBankAccountModel;
