/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

const models = require('./index');

/**
 * Wallet Model
 *
 */
class WalletModel {
  /**
   * Create a WalletModel.
   * @member {number} id Gets or sets the identifier.
   * @member {string} [defaultToken] Gets or sets the default token.
   * @member {array} [creditCards] Gets or sets the credit cards.
   * @member {array} [bankAccounts] Gets or sets the bank accounts.
   */
  constructor() {
  }

  /**
   * Defines the metadata of WalletModel
   *
   * @returns {object} metadata of WalletModel
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'WalletModel',
      type: {
        name: 'Composite',
        className: 'WalletModel',
        modelProperties: {
          id: {
            required: true,
            serializedName: 'id',
            type: {
              name: 'Number'
            }
          },
          defaultToken: {
            required: false,
            serializedName: 'defaultToken',
            type: {
              name: 'String'
            }
          },
          creditCards: {
            required: false,
            serializedName: 'creditCards',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'CreditCardModelElementType',
                  type: {
                    name: 'Composite',
                    className: 'CreditCardModel'
                  }
              }
            }
          },
          bankAccounts: {
            required: false,
            serializedName: 'bankAccounts',
            type: {
              name: 'Sequence',
              element: {
                  required: false,
                  serializedName: 'BankAccountModelElementType',
                  type: {
                    name: 'Composite',
                    className: 'BankAccountModel'
                  }
              }
            }
          }
        }
      }
    };
  }
}

module.exports = WalletModel;
