/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Wallet Bank Account Request Model
 *
 */
class WalletBankAccountRequestModel {
  /**
   * Create a WalletBankAccountRequestModel.
   * @member {string} [paymentToken] Gets or sets the payment token.
   * @member {boolean} [isDefault] Gets or sets a value indicating whether this
   * instance is default.
   */
  constructor() {
  }

  /**
   * Defines the metadata of WalletBankAccountRequestModel
   *
   * @returns {object} metadata of WalletBankAccountRequestModel
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'WalletBankAccountRequestModel',
      type: {
        name: 'Composite',
        className: 'WalletBankAccountRequestModel',
        modelProperties: {
          paymentToken: {
            required: false,
            serializedName: 'paymentToken',
            type: {
              name: 'String'
            }
          },
          isDefault: {
            required: false,
            serializedName: 'isDefault',
            type: {
              name: 'Boolean'
            }
          }
        }
      }
    };
  }
}

module.exports = WalletBankAccountRequestModel;
