/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * Wallet Request Model
 *
 */
class WalletRequestModel {
  /**
   * Create a WalletRequestModel.
   * @member {string} [referenceId] Gets or sets the reference identifier.
   */
  constructor() {
  }

  /**
   * Defines the metadata of WalletRequestModel
   *
   * @returns {object} metadata of WalletRequestModel
   *
   */
  mapper() {
    return {
      required: false,
      serializedName: 'WalletRequestModel',
      type: {
        name: 'Composite',
        className: 'WalletRequestModel',
        modelProperties: {
          referenceId: {
            required: false,
            serializedName: 'referenceId',
            type: {
              name: 'String'
            }
          }
        }
      }
    };
  }
}

module.exports = WalletRequestModel;
